
[features]

	[features.hanging_signs]
		#Allows placing items on hanging signs
		items_on_signs = true

	[features.cauldron]
		#Enables enhanced cauldron
		enabled = true
		#Allows crafting items using cauldrons by clicking on them
		crafting = true
		#Allows dying cauldron water bedrock style and mixing them too
		dye_water = true
		#Max amount of items that 1 cauldron layer can recolor.This is a multiplier on top of vanilla crafting recipe amount
		#Range: 1 ~ 64
		dye_recipes_per_layer = 8
		#Max amount of items that 1 cauldron layer can craft with potions.This is a multiplier on top of vanilla crafting recipe amount
		#Range: 1 ~ 64
		potion_recipes_per_layer = 2
		#Allows mixin potions in cauldrons
		#Allowed Values: OFF, ONLY_BOILING, ON
		potions_mixing = "ON"
		#Makes cauldrons connect to fences
		connect_to_fences = true

	[features.carpeted_blocks]
		#Allows you to place carpets on stairs
		carpeted_stairs = true
		#Allows you to place carpets on slabs
		carpeted_slabs = true

	[features.cake]
		#Allows you to place a cake on top of another
		double_cake = true
		#Allows eating a cake from every side
		directional_cake = true

	[features.mob_head]
		#Allows you to place two mob heads on top of each other
		skull_piles = true
		#Allows candles to be placed on top of skulls
		skull_candles = true
		#Allows placing more than one candle ontop of each skull
		multiple_candles = true

	[features.flower_pot]
		#allows you to place hanging flower pots. Works with any modded pot too
		hanging_pot = true

	[features.lantern]
		#Allow wall lanterns placement
		enabled = true
		#Gives high priority to wall lantern placement. Enable to override other wall lanterns placements, disable if it causes issues with other mods that use lower priority block click events
		high_priority = true
		#Mod ids of mods that have lantern block that extend the base lantern class but don't look like one
		mod_blacklist = ["extlights", "betterendforge", "tconstruct", "enigmaticlegacy", "beautify"]
		#Allows ceiling lanterns to fall if their support is broken.Additionally if they fall from high enough they will break creating a fire where they land
		#Allowed Values: ON, OFF, NO_FIRE
		falling_lanterns = "ON"

	[features.bell]
		#Ring a bell by clicking on a chain that's connected to it
		chain_ringing = true
		#Max chain length that allows a bell to ring
		#Range: 0 ~ 256
		chain_length = 16

	[features.banners]
		#Allow banners to be placed on ceilings
		ceiling_banners = true

	[features.misc]
		#Allows dying blocks by right clicking them with dye
		dye_blocks = false

	[features.lily_pad]
		#Allows lilypads to have any block placed ontop
		better_lilypads = true

