
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 980595
	#The name of the modpack
	modpackName = "Create Chronicles: Bosses and Beyond"
	#The version of the modpack
	modpackVersion = "1.5.0"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

