#.
#Enables/Disables the conversion of placed copycats from the single material to the multi material(where applicable) block entity. Set this to false to enable conversion! (only happens on world load, so if changed while ingame you will need to load the world again)
disableConversion = true

#.
#Enable/disable features. Values on server override clients
[features]
	copycat_board = false
	copycat_wooden_button = true
	copycat_trapdoor = true
	copycat_stone_pressure_plate = true
	copycat_byte = true
	copycat_half_panel = true
	copycat_vertical_slice = false
	copycat_slice = true
	copycat_wooden_pressure_plate = true
	copycat_block = false
	copycat_beam = false
	copycat_fence = false
	copycat_wall = false
	copycat_vertical_step = false
	copycat_light_weighted_pressure_plate = true
	copycat_heavy_weighted_pressure_plate = true
	copycat_half_layer = true
	copycat_stairs = false
	copycat_fence_gate = false
	copycat_stone_button = true
	copycat_layer = true
	copycat_slab = false
	copycat_ghost_block = true
	copycat_ladder = true
	#.
	copycat_vertical_stairs = true
	copycat_shaft = true
	copycat_slope_layer = true
	copycat_slope = true
	copycat_vertical_slope = true

#.
#Enable/disable categories of features. Disabling a category hides all related features. Values on server override clients
[feature_categories]
	#.
	#.
	#All copycats with a sloped surface
	slopes = true
	#.
	#All copycats that support multiple materials in a single block
	multistates = true
	#.
	#All copycats that can be resized by putting in more of the same copycat
	stackables = true
	#.
	#All copycats that can emit a redstone signal
	redstone = true

