#If true, fake players will allow mobs to drop trophies.
#This can allow mob grinders from other mobs to drop trophies, such as the mob masher from MobGrindingUtils.
fake_player_drops = false
#If true, allows trophies to drop whenever a mob dies. This can be to fall damage, another mob, etc.
#Basically, a kill doesnt have to count as a player kill for a trophy to drop.
any_kill_drops = false
#The chance a trophy will drop from its respective mob.
#All trophy drop chances are defined in their trophy json, but if you want to override that chance without going through and changing every json this is for you.
#This value works as a percentage (number * 100), so 0.2 would be a 20% chance for example.
#Set this value to any negative number to disable the override.
#Range: -1.0 ~ 1.0
trophy_drop_override = 0.01
#The chance a player will drop a trophy when killed by a charged creeper.
#This config mostly exists for singleplayer worlds where getting a player kill on a player is rather difficult.
#This value works as a percentage (number * 100), so 0.2 would be a 20% chance for example.
#Set this value to 0.0 to disable drops from charged creeper kills.
#Range: 0.0 ~ 1.0
charged_creeper_player_trophy_chance = 0.4

